---
- name: Habilitamos en UFW la conexi칩n a mariadb
  community.general.ufw:
  rule: allow
  port: '3306'
  protocol: tcp
  direction: in

- name: Configuraci칩n de servidor base de datos en Ubuntu
  hosts: database
  become: true
  user: sysadmin

  tasks:

  - name: UFW instalado
    ansible.builtin.apt:
      name: ufw
      state: present

  - name: Permitir puerto 22 en UFW
    community.general.ufw:
      rule: allow
      name: OpenSSH

  - name: Definimos politicas de tr치fico saliente
    community.general.ufw:
      policy: allow
      direction: outgoing
      state: enabled

  - name: Definimos politicas de tr치fico entrante
    community.general.ufw:
      policy: deny
      direction: incoming
      state: enabled

  - name: Servicio UFW levantado y activo
    ansible.builtin.systemd_service:
      name: ufw
      state: started
      enabled: true