---
- name: Hardening de servidores Centos
  hosts: centos
  become: true
  user: sysadmin

  tasks:

    - name: Configuración de opciones de seguridad de SSH
      ansible.builtin.lineinfile: 
        path: /etc/ssh/sshd_config
        regexp: '^#PermitRootLogin'
        line: PermitRootLogin no
      notify: Reinicio servidor ssh
      register: results_sshd

  handlers:

  - name: Reinicio servidor SSH
    ansible.builtin.systemd_service:
      name: "sshd"
      state: restarted