---
- name: Hardening de servidores centos
  hosts: centos
  become: true
  user: sysadmin

  tasks:

  - name: Configuro opciones de seguridad de ssh
    ansible.builtin.lineinfile: 
      path: /etc/ssh/sshd_config
      regexp: '^#PermitRootLogin'
      line: PermitRootLogin no
    notify: Reinicio servidor ssh
    register: results_sshd

  handlers:

  - name: Reinicio servidor ssh
    ansible.builtin.systemd_service:
      name: "sshd"
      state: restarted