---
- name: Instalar y configurar un webserver
  hosts: centos
  become: true
  user: sysadmin

  tasks:
  
  - name: Instalar tar
    ansible.builtin.dnf:
      name: tar
      state: present

  - name: Instalar apache
    ansible.builtin.dnf:
      name: httpd
      state: present

  - name: Crear directorio tomcat
    ansible.builtin.file:
      path: /opt/tomcat
      state: directory
      mode: '0755'
      owner: apache
      group: apache

  - name: Copy file with owner and permissions TODO
    ansible.builtin.copy:
     src: /home/sysadmin/todo.war
     dest: /opt/tomcat/webapps/
     owner: apache
     group: apache
     mode: '0755'

  - name: Crear directorio config
    ansible.builtin.file:
      path: /opt/config
      state: directory
      mode: '0755'
      owner: apache
      group: apache

  - name: Copy file with owner and permissions APP.PROPERTIES
    ansible.builtin.copy:
     src: /home/sysadmin/app.properties
     dest: /opt/config/
     owner: apache
     group: apache
     mode: '0755'

  - name: Permito conexiones al puerto 80
    ansible.posix.firewalld:
      port: "{{ item }}"
      state: enabled
      immediate: true
      permanent: true
    loop: 
      - 80/tcp
      - 443/tcp
      - 8080/tcp
      

  - name: Apache levantado y habilitado
    ansible.builtin.systemd_service:
      name: httpd
      state: started
      enabled: true

  - name: Tomcat levantado y habilitado
    ansible.builtin.systemd_service:
      name: tomcat
      state: started
      enabled: true

  handlers:

  - name: Reiniciar apache
    ansible.builtin.systemd_service:
      name: httpd
      state: restarted

  - name: Reiniciar tomcat
    ansible.builtin.systemd_service:
      name: tomcat
      state: restarted