---
- name: Instalo servidor tomcat
  hosts: centos
  user: sysadmin
  become: true

  tasks:

  - name: Instalar tar
    ansible.builtin.dnf:
      name: tar
      state: present

  - name: Instalar JAVA
    ansible.builtin.dnf:
      name: java-11-openjdk
      state: present
    
  - name: Descargo el paquete tomcat
    ansible.builtin.uri: 
      url: "https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.91/bin/apache-tomcat-9.0.91.tar.gz"
      dest: /opt/
    register: tomcat_file

  - name: Descomprimo el archivo de tomcat
    ansible.builtin.unarchive:
      src: "{{ tomcat_file.path }}"
      dest: /opt
      remote_src: true 

  - name: Seteo variable con ruta donde está el tomcat
    ansible.builtin.set_fact:
      dir_tomcat: "{{ tomcat_file.path | splitext | first | splitext | first }}" 
  - name: Creo enlace a tomcat
    ansible.builtin.file:
      src: "{{ dir_tomcat }}"
      dest: /opt/tomcat
      state: link
      force: true


  - name: Copia del archivo tomcat
    ansible.builtin.copy:
      src: ./files/tomcat.service
      dest: /etc/systemd/system/
      owner: root
      group: root
      mode: '0755'

      
  handlers:

  - name: Reinicar systemctl
    ansible.builtin.systemd_service:
     daemon_reload: true      