[centos]
#centos1 ansible_host=192.168.56.22
centos2 ansible_host=192.168.56.30

[ubuntu]
#ubuntu1 ansible_host=192.168.56.21
ubuntu2 ansible_host=192.168.56.31

[database]
ubuntu1
ubuntu2

[linux:children]
centos
ubuntu