[centos]
centos1 ansible_host=192.168.56.22
centos3 ansible_host=192.168.56.40

[ubuntu]
ubuntu1 ansible_host=192.168.56.21
ubuntu3  ansible_host=192.168.56.41

[database]
ubuntu1
ubuntu3

[linux:children]
centos
ubuntu